### ISSUE TITLE
CI build is broken

### ISSUE THREAD

**Issue by pmonks** [finos/finos.github.io#29]
See [errors on Travis](https://travis-ci.com/finos/finos.github.io).

**Comment by maoo** [comment]
Build was already disabled, after this log came in; please note that:
- This error was caused by Travis CI being enabled by default on all GitHub projects (regardless they have a .travis.yml)
- travis-ci.com is private and not used by the community.

Please ignore any issue coming from travis-ci.com for the future! TY!
